{% set name = "output_viewer" %}
{% set version = "1.3.2" %}
package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/esgf/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 2c70e9b309831ce5988b44f617a24568686820e9dfc5b2430ff72ef4e3d233a7

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6,<3.8
    - setuptools
    - requests
    - pip
  run:
    - python >=3.6,<3.8
    - requests

test:
  imports:
    - output_viewer

about:
  home: https://github.com/esgf/output_viewer
  summary: |
    The Output Viewer is designed to provide a framework for viewing arbitrary
    output from diagnostics scripts, metrics, or any program that produces a
    ton of different files that you want to look at it in an easy-to-use
    fashion.
  license: ESGF
  license_file: LICENSE

extra:
  recipe-maintainers:
    - doutriaux1
    - zshaheen
    - xylar
    - chengzhuzhang
    - forsyth2
    - muryanto1
