{% set name = "output_viewer" %}
{% set version = "1.2.6" %}
package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/esgf/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 262b83dfd6fae91e37c0f29054c4a2d3c3dcacda0584b6db54035f402112ade3

build:
    number: 0
    noarch: python
    script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python {{ python }}
    - setuptools
    - requests
    - pip
  run:
    - python {{ python }}
    - requests

test:
   imports:
       - output_viewer

about:
  home: https://github.com/esgf/output_viewer
  summary: The Output Viewer is designed to provide a framework for viewing arbitrary output from diagnostics scripts, metrics, or any program that produces a ton of different files that you want to look at it in an easy-to-use fashion.
  license: ESGF
  license_file: LICENSE

extra:
    recipe-maintainers:
        - doutriaux1
        - zshaheen
