travis:
  secure:
    BINSTAR_TOKEN: NiVP2YJnFEYoXiRGxSkL2Dqsg2vWVWZOS/+Imv6hpmBzd2dH7d7Jpw2HwPzrZ+tHbH9etJMt/MMWrdg8Cqmry7XqSk9KKJk2DzZybmGxsfsMe6o/YMqtoD5/QmaxZrb7BswyeNG+bGbZvy/rbLK0W4zI/9bMLkk/Z9FxYvCf1KNZSwjRiwY4QhvkLz42xeA9KNhrL4k7wzK0mhl407z3JfhnKuOi0zJz552T900mrAFENaBR21nOkCOmIXXQNSNk0iD0l9db7hlGedTxhvaSyHUrCXyfAeIjt8vrit5tyX7mt/poh23S2pADOgbyywVnq1rbyirtrCCNBwEEx7bTFWJGCF3hTYH4unlfcY+TH+Dt9RFAq8BOxxyGRbE7/O2E1DtBJDaA+BezBe/0idHKSiWt9WcIhyQcRGKWkToWOG2+o+UPreba3aSLf18XxHxjwMgFAryAtM7L1chPsHohDpQ6/7u2eM/F1MY3ofsCLI1eBwGYh4THi1z3j2tT3negrfoUVeQyM5+93e1+RhAP+QGJ/CTdHKLcIAxNltgtcuNZjTeD7paMFc8/diaGzDSL3eHEOEv51wXM1e/3Zo3Gp6T7RODlN4KH+de1vzPfb2BBldVrpO//5diyeMqF6nTH3wJbrrtmgkIg+EJNSgjpPPwofplwbhZ7OJpMUOQJsv8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
