travis:
  secure:
    BINSTAR_TOKEN: Evb/S5vIf61kwiOVhmhgAjLpVia6etbco0Stk3fTjALc3dHsFs94LWzV8MGUMKQ7bIYt8eQsGD0X3leCKGU3/JMPWCgJnTDbOazAQLaAKzmIhIFiWOhapNV4FWh9beIfE7IUFLHhraGdpXz7Wln8olqOTWtpAHb6mxNOwExnk33Rb9Is+0X41fqqCTDU9x4rISXc5iTjiDakilRoZKlS0sbEUuXcrxchzGOlL9lxy+HazU0UAhwR6sLJHecvhkY3ATJSOr/iuWRVCzXOBGMboHCiSNbQPDhz6VgIng/wpWJzRBlTPOEVafq59MSU3bvMg6cSTgzor6VjL9pH+YBPoQhZaQ9UWRRK12ezSl8X8G8OEmPyU5IgQZ0hsPdvbub2RnH1bn9qb8VbHpFNna670RCvqtGBRgi8o2BaMlcMCW6Kb+5ipMMpQMmVcMO2d241QS/hHTZZ3xAlv5dcVHqOSNfCId9/5hIPyejM5jzEaLGsXHCEVPHstT3NA6eb4l192+1w0B6zxjt3+AONAjlAY3lRiW7ZEvPrlBSbINH5FxbaAFf26oW6buTFjtbWQijJraYLJDmEFb8KsAsTKTcSKjo+uO7v9j6l1Ei2qeEZi+y+6CJcDKVBwVwXwMJmZaMORiv6ChpqZB4DzzUpBWzIApAyeyvODTIl62MhqbH2l4I=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
